In [340]:
import numpy as np


In [418]:
# example
nwalks=5000
nsteps=1000
draws=np.random.randint(0,2,size=(nwalks,nsteps))
steps=np.where(draws>0,1,-1)
walks=steps.cumsum(1)
print(walks)
print(walks.max())
print(walks.min())
hit30=(np.abs(walks)>=30).any(1)
print(hit30)
print(hit30.sum())
crossing_times=(np.abs(walks[hit30])>=30)

[[  1   0  -1 ... -20 -19 -20]
 [ -1   0  -1 ...  10  11  10]
 [ -1  -2  -1 ... -20 -21 -22]
 ...
 [  1   0  -1 ...  -6  -7  -8]
 [  1   0   1 ... -68 -69 -68]
 [  1   2   1 ...  -6  -7  -8]]
116
-119
[False False False ... False False False]
9


In [341]:
# example
nsteps=1000
draws=np.random.randint(0,2,size=nsteps)
steps=np.where(draws>0,1,-1)
walk=steps.cumsum()
print(walk.min())
print(walk.max())

-27
9


In [342]:
# example
import random
position=0
walk=[position]
steps=1000
for i in range(steps):
    step=1 if random.randint(0,1) else -1
    position+=step
    walk.append(position)

In [343]:
from numpy.linalg import inv,qr

x=np.random.randn(5,5)
print(x)
x=x.T.dot(x)
print(x.dot(inv(x)))


[[-0.17616325 -0.16641482 -1.35695763 -0.54890316  0.06113484]
 [-0.71471261  0.64578238  0.77790084 -2.83027716 -0.5187083 ]
 [-1.66582143 -0.47691461  0.45301731 -0.61084629  0.57599753]
 [ 0.83299087 -0.86780366  1.34780852  0.86103802 -0.5382163 ]
 [-2.65162384  1.26145071  1.41573497 -0.82463059 -0.59820675]]
[[ 1.00000000e+00 -6.16062296e-16 -2.45548381e-16 -1.64782166e-18
  -1.18066907e-15]
 [ 3.57152663e-17  1.00000000e+00  8.11542664e-17 -4.55822888e-17
   5.35871597e-16]
 [ 1.12823286e-16  1.65032106e-16  1.00000000e+00 -5.69609229e-17
   9.02637736e-16]
 [ 1.36208583e-16 -3.06976515e-16  1.08948288e-16  1.00000000e+00
  -2.31845266e-16]
 [-5.10603876e-18 -1.63377542e-16 -6.35351592e-17  8.74538348e-18
   1.00000000e+00]]


In [344]:
x=np.arange(6).reshape((2,3))
y=np.arange(7,13).reshape((3,2))
print(x)
print(y)
x.dot(y)

[[0 1 2]
 [3 4 5]]
[[ 7  8]
 [ 9 10]
 [11 12]]


array([[ 31,  34],
       [112, 124]])

In [345]:
# 其他方法
arr=np.random.randn(10)
(arr>0).sum()

2

In [346]:
# 基本统计函数
arr=np.random.randn(5,4)
print(arr)
# mean，算数平均数
print(arr.mean())
print(np.mean(arr))
print(arr.sum())
print(arr.mean(axis=1))
print(arr.sum(0))
# P105

[[-0.39702202  0.4782717  -1.59878224 -1.19640688]
 [ 0.03875854  0.65142237  2.64965496  0.35774131]
 [ 4.42342746  0.55671088 -1.42918145  1.30671274]
 [-0.1741196   0.47898997 -0.23758289  0.57737548]
 [-0.16989848 -1.02875645  1.08258841 -0.59878501]]
0.28855593971306276
0.28855593971306276
5.771118794261255
[-0.67848486  0.92439429  1.21441741  0.16116574 -0.17871288]
[3.72114589 1.13663847 0.4666968  0.44663763]


In [347]:
# 条件逻辑转化为数组运算
xarr=np.arange(1,1.5,0.1)
yarr=np.arange(2,2.5,0.1)
cond=np.array([True,False,True,False,True])
result=[(x if c else y)for x,y,c in zip(xarr,yarr,cond)]
print(result)


# where函数的作用：第一个为判断条件，第二个为true的赋值，第三个为false的赋值，即;if c 则x else y
# 可以使用where写组合嵌套的语句来实现if的嵌套调用
result=np.where(cond,xarr,yarr)
print(result)


arr=np.random.randn(4,4)
np.where(arr>0,2,-2)


[1.0, 2.1, 1.2000000000000002, 2.3000000000000003, 1.4000000000000004]
[1.  2.1 1.2 2.3 1.4]


array([[ 2, -2,  2,  2],
       [-2, -2,  2, -2],
       [-2, -2,  2,  2],
       [-2, -2, -2, -2]])

In [348]:
# 初步处理数据
points=np.arange(-5,5,0.01)
xs,ys=np.meshgrid(points,points)
# meshgrid:输入两个一维数组，产生两个互相对应的二维矩阵
print(ys)
print(xs)

import matplotlib.pyplot as plt
z=np.sqrt(xs**2+ys**2)
plt.imshow(z,cmap=plt.cm.gray)
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2+y^2}$ for a grid of values")


[[-5.   -5.   -5.   ... -5.   -5.   -5.  ]
 [-4.99 -4.99 -4.99 ... -4.99 -4.99 -4.99]
 [-4.98 -4.98 -4.98 ... -4.98 -4.98 -4.98]
 ...
 [ 4.97  4.97  4.97 ...  4.97  4.97  4.97]
 [ 4.98  4.98  4.98 ...  4.98  4.98  4.98]
 [ 4.99  4.99  4.99 ...  4.99  4.99  4.99]]
[[-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 ...
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]]


Text(0.5,1,'Image plot of $\\sqrt{x^2+y^2}$ for a grid of values')

In [349]:
#     通用函数
arr=np.arange(10)
# 开方
print(np.sqrt(arr))
# exp
print(np.exp(arr))
# maximum
x=np.random.randn(8)
y=np.random.randn(8)
print(np.maximum(x,y))
# 返回浮点数的小数部分和整数部分
arr=np.random.randn(7)*5
print(arr)
print(np.modf(arr))


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[ 2.20482219  0.10724594  0.31952684  0.2403623   1.61432893 -0.42471737
 -0.9793813   0.72904903]
[  6.03008777  -4.97274923  -1.52196036   1.85489625 -10.89409552
  -2.06277111  -4.59852586]
(array([ 0.03008777, -0.97274923, -0.52196036,  0.85489625, -0.89409552,
       -0.06277111, -0.59852586]), array([  6.,  -4.,  -1.,   1., -10.,  -2.,  -4.]))


In [350]:
#     数组转置和轴对换
arr=np.arange(15).reshape((3,5))
print(arr)
print(arr.T)


arr=np.random.randn(6,3)
print(np.dot(arr.T,arr))
arr=np.arange(16).reshape((2,2,4))
print(arr)
print()
print(arr.transpose((1,0,2)))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 1.92295924 -1.22773568 -1.79295662]
 [-1.22773568  4.97784327  3.46171028]
 [-1.79295662  3.46171028  5.54209004]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [351]:
print("#       布尔型索引")
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
print(names)
print(data)
print(names=='Bob')
print(data[names=='Bob'])


#       布尔型索引
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.35813348  0.40904335  1.44879517  2.52538182]
 [-1.25084473  1.56911112 -0.01741575  0.72938804]
 [ 1.74571192 -1.11463884  0.48158281 -1.79494532]
 [ 1.18924718  2.24703057 -0.41192085  1.66313516]
 [ 1.43616206 -1.44751242  0.39246687 -0.83484175]
 [-1.25195733 -0.32455661 -0.64727746 -0.98289653]
 [-1.17574155 -3.07374432 -0.33113966 -1.22248128]]
[ True False False  True False False False]
[[ 0.35813348  0.40904335  1.44879517  2.52538182]
 [ 1.18924718  2.24703057 -0.41192085  1.66313516]]


In [352]:
print("#     索引和切片")
arr=np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])   #    [5:8]为第6，7，8个，即(5:8]

arr[5:8]=12
print(arr)

print("#      切片的数据会反应到源数据上面去")
test_slice=arr[5:8]
test_slice[1]=666
print(test_slice)
print(arr)


print('#     如果想要复制则：')
copy_slice=arr[5:8].copy()
copy_slice[2]=0
print(copy_slice)
print(arr)
print('#     对于高维数组，切片是可以选取多个轴，即：')
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[:2])
print(arr2d[:2,1:])

print("#          得到更低维度的切片,通过切片和索引的结合")
print(arr2d[1,:2])


#     索引和切片
[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
#      切片的数据会反应到源数据上面去
[ 12 666  12]
[  0   1   2   3   4  12 666  12   8   9]
#     如果想要复制则：
[ 12 666   0]
[  0   1   2   3   4  12 666  12   8   9]
#     对于高维数组，切片是可以选取多个轴，即：
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
#          得到更低维度的切片,通过切片和索引的结合
[4 5]


In [353]:
#    数组和标量间的运算,即加减乘除，开方
arr=np.array([[1.,2.,3.],[4.,5.,6.]])
print (arr)
print(arr*arr)
print(arr-arr)
print(1/arr)
print(arr**0.5)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [354]:
#     创建数组以及数组的一些参数



data1=[6,7.5,8,0,1]
arr1=np.array(data1)
print(arr1)
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr1.dtype)
print(arr2.dtype)
arr2=np.asarray(arr2)
print(arr2)
print (np.ones_like(arr2))
print(np.eye(3))
print(np.identity(3))



zero_array=np.zeros(10)
print(zero_array)
ont_array=np.ones(10)
print(ont_array)
zero_array2=np.zeros((5,3))
print(zero_array2)
empty_array=np.empty((1,2,3))
print(empty_array)


print (np.arange(10))

[6.  7.5 8.  0.  1. ]
[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
float64
int64
[[1 2 3 4]
 [5 6 7 8]]
[[1 1 1 1]
 [1 1 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[1.         1.41421356 1.73205081]
  [2.         2.23606798 2.44948974]]]
[0 1 2 3 4 5 6 7 8 9]


In [355]:
#     显式转换dtype
arr=np.array([1,2,3,4,5])
print(arr.dtype)
float_arr=arr.astype(np.float64)
print(float_arr.dtype)


arr=np.array([1.1,2.2,3.9])
arr=arr.astype(np.int64)
print(arr)

arr=np.array(["111","121"])
arr=arr.astype(np.int64)
print(arr)

arr=np.array(["1.11","121"])
arr=arr.astype(np.float)
print(arr)

arr=np.array([11,22,39])
arr=arr.astype(np.string_)
print(arr)



int64
float64
[1 2 3]
[111 121]
[  1.11 121.  ]
[b'11' b'22' b'39']
